name: CI-Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Extract DOCKER_TAG using tag name
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "DOCKER_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Use default DOCKER_TAG
      if: startsWith(github.ref, 'refs/tags/') != true
      run: |
        echo "DOCKER_TAG=latest" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v3
      if: env.DOCKER_USERNAME != null
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set docker tag list to include DockerHub if credentials available
      if: env.DOCKER_USERNAME != null
      run: |
        echo "DOCKER_TAG_LIST=ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }},${{ github.repository }}:${{ env.DOCKER_TAG }}" >> $GITHUB_ENV

    - name: Set docker tag list to not include DockerHub if credentials not available
      if: env.DOCKER_USERNAME == null
      run: |
        echo "DOCKER_TAG_LIST=ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }}" >> $GITHUB_ENV

    - name: Build and Push to container registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.DOCKER_TAG_LIST }}
        build-args: |
          BASE_DOCKER_IMAGE=ghcr.io/${{ github.repository_owner }}/ps2sdk-ports:${{ env.DOCKER_TAG }}

    - name: Send Compile action
      run: |
        export DISPATCH_ACTION="$(echo run_build)"
        echo "NEW_DISPATCH_ACTION=$DISPATCH_ACTION" >> $GITHUB_ENV

    - name: "create payload with this repository payload"
      if: ${{ github.event_name }} != 'repository_dispatch'
      run: |
        export REPO_PAYLOAD="$(echo {\"ref\": \"${{ github.ref }}\", \"parent\": \"${{ github.repository }}\", \"parent_sha\": \"${{ steps.slug.outputs.sha8 }}\"})"
        echo "NEW_REPO_PAYLOAD=$REPO_PAYLOAD" >> $GITHUB_ENV

    - name: "create payload with parent repository payload"
      if: ${{ github.event_name }} == 'repository_dispatch'
      run: |
        export REPO_PAYLOAD="$(echo {\"ref\": \"${{ github.ref }}\", \"parent:\" \"${{ github.event.client_payload.parent }}\", \"parent_sha\": \"${{ github.event.client_payload.parent_sha }}\"})"
        echo "NEW_REPO_PAYLOAD=$REPO_PAYLOAD" >> $GITHUB_ENV

    - name: Repository Dispatch to ps2homebrew ps2dev_forwarder to do broadcast over there
      uses: peter-evans/repository-dispatch@v3
      if: env.DISPATCH_TOKEN != null
      with:
        repository: ps2homebrew/ps2dev_forwarder
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: ${{ env.NEW_DISPATCH_ACTION }}
        client-payload: '${{ env.NEW_REPO_PAYLOAD }}'
